config/routes.rb
Rails.application.routes.draw do
  devise_for :librarians
  root 'books#index'
  resources :reservations
  resources :books
  resources :authors
  resources :categories
  resources :librarians
  resources :clients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/author.rb
class Author < ApplicationRecord
    validates :name, presence:true
    has_many :books, dependent: :destroy
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_librarian!, except: [:index, :show]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
    @button_name = "Create Author"
  end

  # GET /authors/1/edit
  def edit
    @button_name = "Update Author"
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end  
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def author_params
      params.require(:author).permit(:name)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<%= form_with(model: author, local: true) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <section class="content">
    <div class="box box-primary">
      
      <div class="box-body">
        <div class="form-group">
          <label for="author_name">Name</label>
          <input class="form-control" placeholder="Author name" type="text" name="author[name]" id="author_name" />
        </div>
      </div>

      <div class="box-body">
        <button class="btn btn-primary" data-toggle="control-sidebar">
          <%= @button_name%>
          <% form.submit %>
        </button>
      </div>
    </div>
  </section>    
  
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<% @button_name = "Update Author" %>
<%= render 'form', author: @author %>

<a class="btn btn-default" data-toggle="control-sidebar" href="/authors">Back</a> |
<a class="btn btn-info" data-toggle="control-sidebar" style="color: white;" href="/authors/<%=@author.id%>">Show</a>

app/views/authors/index.html.erb
<body class="skin-blue sidebar-mini fixed <%= params[:controller].parameterize %> <%= action_name %>">

    <!-- Main content -->
    <section class="content">
      
      <p id="notice"><%= notice %></p>

      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Authors</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
          <table class="table table-bordered">
            <thead>
              <tr>
                <th>Name</th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <% @authors.each do |author| %>
                <tr>
                  <td><%= author.name %></td>
                  <td><%= link_to 'Show', author %></td>
                  <td><%= link_to 'Edit', edit_author_path(author) %></td>
                  <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
      <%= yield %>
    </section><!-- /.content -->

    <br>

    <a class="btn btn-primary" style="color: white;" href="/authors/new">New Author</a>
    
    
</body>

app/views/authors/new.html.erb
<h1>New Author</h1>

<% @button_name = "Create Author" %>
<%= render 'form', author: @author %>


<a class="btn btn-default" data-toggle="control-sidebar" href="/authors">Back</a>

app/views/authors/show.html.erb
<h1>Showing Author</h1>
<section class="content">

  <p id="notice"><%= notice %></p>


  <div class="box box-primary">

    <div class="box-body">
      <table class="table table-bordered">
        <tbody>
          <tr>
            <td><strong>Name</strong></td>
            <td><%= @author.name %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>    
</section>

<a class="btn btn-default" data-toggle="control-sidebar" href="/authors">Back</a> |
<a class="btn btn-info" data-toggle="control-sidebar" style="color: white;" href="/authors/<%=@author.id%>/edit">Edit</a>