config/routes.rb
Rails.application.routes.draw do
  devise_for :librarians
  root 'books#index'
  resources :reservations
  resources :books
  resources :authors
  resources :categories
  resources :librarians
  resources :clients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_librarian!, except: [:index, :show]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Categorie.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Categorie.new
    @button_name = "Create Category"
  end

  # GET /categories/1/edit
  def edit
    @button_name = "Update Category"
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Categorie.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Categorie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <section class="content">
    <div class="box box-primary">
      
      <div class="box-body">
        <div class="form-group">
          <label for="category_name">Name</label>
          <input class="form-control" placeholder="Category name" type="text" name="category[name]" id="category_name" />
        </div>
      </div>

      <div class="box-body">
        <button class="btn btn-primary" data-toggle="control-sidebar">
          <%= @button_name%>
          <% form.submit %>
        </button>
      </div>
    </div>
  </section>    
  
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<% @button_name = "Update Category" %>
<%= render 'form', category: @category %>

<a class="btn btn-default" data-toggle="control-sidebar" href="/categories">Back</a> |
<a class="btn btn-info" data-toggle="control-sidebar" style="color: white;" href="/categories/<%=@category.id%>">Show</a>

app/views/categories/index.html.erb
<body class="skin-blue sidebar-mini fixed <%= params[:controller].parameterize %> <%= action_name %>">

    <!-- Main content -->
    <section class="content">
      
      <p id="notice"><%= notice %></p>

      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Categories</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
          <table class="table table-bordered">
            <thead>
              <tr>
                <th>Name</th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <% @categories.each do |category| %>
                <tr>
                  <td><%= category.name %></td>
                  <td><%= link_to 'Show', category %></td>
                  <td><%= link_to 'Edit', edit_category_path(category) %></td>
                  <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
      <%= yield %>
    </section><!-- /.content -->

    <br>

    <a class="btn btn-primary" style="color: white;" href="/categories/new">New Category</a>
    
    
</body>

app/views/categories/new.html.erb
<h1>New Category</h1>

<% @button_name = "Create Category" %>
<%= render 'form', category: @category %>

<a class="btn btn-default" data-toggle="control-sidebar" href="/categories">Back</a>

app/views/categories/show.html.erb
<h1>Showing Category</h1>
<section class="content">

  <p id="notice"><%= notice %></p>


  <div class="box box-primary">

    <div class="box-body">
      <table class="table table-bordered">
        <tbody>
          <tr>
            <td><strong>Name</strong></td>
            <td><%= @category.name %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>    
</section>

<a class="btn btn-default" data-toggle="control-sidebar" href="/categories">Back</a> |
<a class="btn btn-info" data-toggle="control-sidebar" style="color: white;" href="/categories/<%=@category.id%>/edit">Edit</a>